### ISSUE TITLE
UnicodeDecodeError in Version 0.3.3 on Ubuntu 16:10 with python 3.5.2 using virtualenv

### ISSUE THREAD

**Issue by bitpick** [daboth/pive#5]
Calling `pip install pive` leads to the following error:

`Downloading pive-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-a310yo8g/pive/setup.py", line 13, in <module>
        long_description=open('README.md').read(),
     File "/var/visquid/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
   UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 121: ordinal not in range(128)`

**Comment by daboth** [comment]
Thank you for the report! Fixed with e1882b30a684c05e189a8fd870fda08c665793ab
